### ISSUE TITLE
Tutorial or comand to use it on vps and client 

### ISSUE THREAD

**Issue by ingnelson** [myzhang1029/penguin-rs#2]
Hello.

Vps server:
Could you give me the command to download and run your program in my vps (1.2.3.4) on port 8080.

Client (Termux terminal app:
Could you give me the command to connect it to my vps (1.2.3.4) on port 8080 and use local host (127.0.0.1) and local port 1080 ? 
This way I can use a  a app (tun2tap for android app) and access to internet with all my android apps.

I am planning to use my android phone as a client using the the Termux terminal app on android . 

Similar to this video : 
https://youtu.be/Rb4OIXWrjNU

I will wait your answer

**Comment by myzhang1029** [comment]
Hi @ingnelson,

Do you have command line access to your VPS? If so, this is the same as any other Rust programs:
1. [Install rust](https://rustup.rs) if you haven't done so.
2. Run `cargo install rusty-penguin`.

I assume you have used `chisel` before. The command line of this program is mostly compatible with `chisel` (though the protocol isn't).

Be aware though, I wrote all these within a week, so don't expect it to be as stable as `chisel`. That said, I've experienced success in my own production environment.
Thanks for your interest in this program and please feel free to reach out for further issues.

**Comment by ingnelson** [comment]
Would be possible you can provide all the commands to install and run your program  liks a server and client ? Please 

Like a mini tutorial , please

**Comment by myzhang1029** [comment]
Okay.
For the server side, I am assuming access to a Linux terminal:
```sh
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh # Install Rust
# After this, you may need to restart the terminal because Rust updates the environmental variables
cargo install rusty-penguin
penguin server --host 1.2.3.4 --port 8080 # put --tls-key <KEY PATH> --tls-cert <PUBLIC CERT CHAIN> for TLS support
```
and it should run.

For the client side, I don't know how you would manage to install Rust on Android. If your device is an ARMv7 Android, it should at least build, according to [Rust docs](https://doc.rust-lang.org/rustc/platform-support.html). Anyways, try executing
```sh
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh # Install Rust
# After this, you may need to restart the terminal because Rust updates the environmental variables
cargo install rusty-penguin
penguin client http://1.2.3.4:8080 127.0.0.1:1080:socks
```
and see what happens.

**Comment by ingnelson** [comment]
i installed rust in Termux using the command :

`pkg install rust`

when i tried to install penguin with the command  `cargo install rusty-penguin` , it shows a error:

**Comment by myzhang1029** [comment]
I have no idea about 
```
error occurred: Failed to find tool. Is `aarch64-linux-android-ar` installed?
```
but for the last error, it is because you did not `git clone` the submodule. If you are using `git` to obtain the code, run
```
git submodule update --init
```

**Comment by ingnelson** [comment]
At the end I installed on Termux (android ) using this commands : 

```
pkg install rust 
pkg install binutils
cargo install rusty-penguin
```

Then I un the next command where it was installed : 

`penguin client http://1.2.3.4:8080/ws 127.0.0.1:1080:socks`


Thanks

**Comment by myzhang1029** [comment]
So things work now?

**Comment by ingnelson** [comment]
Yes , it works
