### ISSUE TITLE
Reverse SOCKS proxy does not work?

### ISSUE THREAD

**Issue by symmetrisch** [myzhang1029/penguin-rs#20]
How do I open a SOCKS listener on the server side? Tried

`sudo ./penguin server --port 443 --tls-cert cert.pem --tls-key privkey.pem --obfs --reverse`

but 

`./penguin client -k wss://example.com/ws socks`

opens :1080 on the client side and 

`./penguin client -k wss://example.com/ws R:socks`

yields 

`error: invalid value 'R:socks' for '<REMOTE>...': Invalid port`

**Comment by myzhang1029** [comment]
Sorry but that is correct. I have not implemented that and it is not planned yet.

**Comment by symmetrisch** [comment]
Understood. Would be great to have this feature someday, speed looks really good with Rust :-)

**Comment by myzhang1029** [comment]
Thanks for the support!
